version: "2.1"

services:
  local_client:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app/client
    env_file:
      - .docker.env
    ports:
      - "3000:3000"
    command: ./compose/start.sh
