version: "2.1"

services:
  react:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/app/client
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
