import url from 'routes/utils';

export const CLIENT_URLS = {
  INDEX: url('/'),
  USER: {
    INDEX: url('/'),
    MENU: url('/menu/'),
    NOTIFICATIONS: url('/notifications/'),
    PROFILE: url('/:userSlug/'),
    POST_CREATE: url('/posts/create/'),
    POST_UPDATE: url('/posts/update/:postSlug/'),
    NEWS_LIST: url('/news/'),
    NEWS_DETAIL: url('/news/:newsPk/'),
    FRIEND_LIST: url('/friends/'),
    FRIEND_REQUESTS: url('/friends/requests/'),
    PARTICIPANT_LIST: url('/participants/'),
    BLACKLIST_LIST: url('/blacklist/'),
    CHAT_LIST: url('/chats/'),
    CHAT_DETAIL: url('/chat/:chatPk/'),
    CHAT_CREATE: url('/chats/create/'),
    CHAT_UPDATE: url('/chats/update/:chatPk/'),
    CHAT_CONVERSATION_CREATE: url('/chats/conversation/:recipientSlug/'),
    CHAT_WITH_MODERATORS_CREATE: url('/chats/support/'),
    GROUP_LIST: url('/groups/'),
    GROUP_DETAIL: url('/group/:groupSlug/'),
    GROUP_CREATE: url('/groups/create/'),
    GROUP_UPDATE: url('/groups/update/:groupSlug/'),
    GROUP_REQUESTS: url('/groups/requests/'),
    GROUP_DETAIL_REQUESTS: url('/groups/requests/:groupSlug/'),
    CLUB_LIST: url('/clubs/'),
    CLUB_DETAIL: url('/club/:clubSlug/'),
    CLUB_CREATE: url('/clubs/create/'),
    CLUB_UPDATE: url('/clubs/update/:clubSlug/'),
    CLUB_REQUESTS: url('/clubs/requests/'),
    CLUB_DETAIL_REQUESTS: url('/clubs/requests/:clubSlug/'),
    PARTY_LIST: url('/parties/'),
    PARTY_DETAIL: url('/party/:partySlug/'),
    PARTY_CREATE: url('/parties/create/'),
    PARTY_UPDATE: url('/parties/update/:partySlug/'),
    MEDIA_FOLDER_LIST: url('/media_folders/'),
    MEDIA_FOLDER_DETAIL: url('/media_folder/:mediaFolderPk/'),
    MEDIA_FOLDER_CREATE: url('/media_folders/create/'),
    MEDIA_FOLDER_UPDATE: url('/media_folders/update/:mediaFolderPk/'),
    MEDIA_FOLDER_DETAIL_MEDIA_CREATE: url('/media_folders/media/create/'),
    MEDIA_FOLDER_DETAIL_MEDIA_UPDATE: url(
      '/media_folders/media/update/:mediaPk/',
    ),
    MEDIA_FOLDER_DETAIL_MEDIA_DETAIL: url(
      '/media_folders/media/detail/:mediaPk/',
    ),
    GAME_LIST: url('/games/'),
    GAME_DETAIL: url('/games/detail/:gameSlug/'),
    GAME_UPDATE: url('/games/update/:gameSlug/'),
    GAME_PLAY: url('/game/:gameSlug/'),
    SETTINGS: url('/settings/'),
  },
  MODERATOR: {
    INDEX: url('/moderator/'),
    MENU: url('/moderator/menu/'),
    CHAT_LIST: url('/moderator/chats/'),
    USER_LIST: url('/moderator/users/'),
    CLUB_LIST: url('/moderator/clubs/'),
    PARTY_LIST: url('/moderator/parties/'),
    POST_LIST: url('/moderator/posts/'),
    MEDIA_LIST: url('/moderator/media/'),
    NEWS_LIST: url('/moderator/news/'),
    NEWS_DETAIL: url('/moderator/news/:newsPk/'),
    NEWS_CREATE: url('/moderator/news/create/'),
    NEWS_UPDATE: url('/moderator/news/update/:newsPk/'),
  },
  SEARCH: url('/search/'),
  WHISPER: url('/whisper/'),
  POSTS: url('/posts/'),
  POSTS_DETAIL: url('/post/:postSlug/'),
  MEDIA: url('/media/'),
  MAP: url('/map/'),
  AUTH: {
    INDEX: url('/auth/'),
    SIGN_IN: url('/auth/sign-in/'),
    SIGN_UP: url('/auth/sign-up/:userPk/'),
    SIGN_UP_FINISH: url('/auth/sign-up/finish/:userPk/'),
    RESET_PASSWORD: url('/auth/reset-password/'),
    RESET_PASSWORD_FINISH: url('/auth/reset-password/finish/:userPk/'),
  },
  SITE_POLICY: url('/policy/'),
  HTTP_PAGES: {
    PAGE_403: url('/403/'),
    PAGE_404: url('/404/'),
  },
};
